//! Ingestion Monitor for tracking data freshness and alerting on failures
//!
//! Provides monitoring for data ingestion pipelines with alerting capabilities.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};

/// Severity levels for ingestion alerts
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

/// An alert generated by the ingestion monitor
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestionAlert {
    /// Alert ID
    pub id: String,
    /// Symbol affected
    pub symbol: String,
    /// Timeframe affected
    pub timeframe: String,
    /// Alert severity
    pub severity: AlertSeverity,
    /// Alert message
    pub message: String,
    /// When the alert was created
    pub created_at: DateTime<Utc>,
    /// Whether the alert has been acknowledged
    pub acknowledged: bool,
}

/// Status of a symbol's data ingestion
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestionStatus {
    /// Symbol being tracked
    pub symbol: String,
    /// Timeframe being tracked
    pub timeframe: String,
    /// Last successful ingestion time
    pub last_success: Option<DateTime<Utc>>,
    /// Last failure time
    pub last_failure: Option<DateTime<Utc>>,
    /// Last failure message
    pub last_failure_message: Option<String>,
    /// Number of consecutive failures
    pub consecutive_failures: u32,
    /// Total successful ingestions
    pub total_successes: u64,
    /// Total failed ingestions
    pub total_failures: u64,
}

/// Configuration for the ingestion monitor
#[derive(Debug, Clone)]
pub struct IngestionMonitorConfig {
    /// How long before data is considered stale (warning)
    pub stale_warning_threshold: Duration,
    /// How long before data is considered critically stale
    pub stale_critical_threshold: Duration,
    /// Number of consecutive failures before alerting
    pub failure_alert_threshold: u32,
}

impl Default for IngestionMonitorConfig {
    fn default() -> Self {
        Self {
            stale_warning_threshold: Duration::hours(2),
            stale_critical_threshold: Duration::hours(6),
            failure_alert_threshold: 3,
        }
    }
}

/// Ingestion monitor for tracking data freshness
pub struct IngestionMonitor {
    config: IngestionMonitorConfig,
    statuses: Arc<RwLock<HashMap<String, IngestionStatus>>>,
    alerts: Arc<RwLock<Vec<IngestionAlert>>>,
}

impl IngestionMonitor {
    /// Create a new ingestion monitor
    pub fn new(config: IngestionMonitorConfig) -> Self {
        Self {
            config,
            statuses: Arc::new(RwLock::new(HashMap::new())),
            alerts: Arc::new(RwLock::new(Vec::new())),
        }
    }

    /// Generate a key for a symbol/timeframe pair
    fn key(symbol: &str, timeframe: &str) -> String {
        format!("{}:{}", symbol, timeframe)
    }

    /// Record a successful ingestion
    pub fn record_success(&self, symbol: &str, timeframe: &str, bars_ingested: usize) {
        let key = Self::key(symbol, timeframe);
        let mut statuses = self.statuses.write().unwrap();

        let status = statuses.entry(key).or_insert_with(|| IngestionStatus {
            symbol: symbol.to_string(),
            timeframe: timeframe.to_string(),
            last_success: None,
            last_failure: None,
            last_failure_message: None,
            consecutive_failures: 0,
            total_successes: 0,
            total_failures: 0,
        });

        status.last_success = Some(Utc::now());
        status.consecutive_failures = 0;
        status.total_successes += 1;

        tracing::info!(
            symbol = %symbol,
            timeframe = %timeframe,
            bars = %bars_ingested,
            "Data ingestion successful"
        );
    }

    /// Record a failed ingestion
    pub fn record_failure(&self, symbol: &str, timeframe: &str, error: &str) {
        let key = Self::key(symbol, timeframe);
        let mut statuses = self.statuses.write().unwrap();

        let status = statuses.entry(key).or_insert_with(|| IngestionStatus {
            symbol: symbol.to_string(),
            timeframe: timeframe.to_string(),
            last_success: None,
            last_failure: None,
            last_failure_message: None,
            consecutive_failures: 0,
            total_successes: 0,
            total_failures: 0,
        });

        status.last_failure = Some(Utc::now());
        status.last_failure_message = Some(error.to_string());
        status.consecutive_failures += 1;
        status.total_failures += 1;

        tracing::error!(
            symbol = %symbol,
            timeframe = %timeframe,
            error = %error,
            consecutive = %status.consecutive_failures,
            "Data ingestion failed"
        );

        // Create alert if threshold exceeded
        if status.consecutive_failures >= self.config.failure_alert_threshold {
            self.create_alert(
                symbol,
                timeframe,
                AlertSeverity::Critical,
                format!(
                    "{} consecutive ingestion failures for {} {}: {}",
                    status.consecutive_failures, symbol, timeframe, error
                ),
            );
        }
    }

    /// Check data freshness for all tracked symbols
    pub fn check_freshness(&self) -> Vec<IngestionAlert> {
        let statuses = self.statuses.read().unwrap();
        let mut new_alerts = Vec::new();
        let now = Utc::now();

        for status in statuses.values() {
            if let Some(last_success) = status.last_success {
                let age = now - last_success;

                if age > self.config.stale_critical_threshold {
                    new_alerts.push(self.create_alert(
                        &status.symbol,
                        &status.timeframe,
                        AlertSeverity::Critical,
                        format!(
                            "Data for {} {} is critically stale (last update: {})",
                            status.symbol,
                            status.timeframe,
                            last_success.format("%Y-%m-%d %H:%M:%S UTC")
                        ),
                    ));
                } else if age > self.config.stale_warning_threshold {
                    new_alerts.push(self.create_alert(
                        &status.symbol,
                        &status.timeframe,
                        AlertSeverity::Warning,
                        format!(
                            "Data for {} {} is stale (last update: {})",
                            status.symbol,
                            status.timeframe,
                            last_success.format("%Y-%m-%d %H:%M:%S UTC")
                        ),
                    ));
                }
            }
        }

        new_alerts
    }

    /// Create and store an alert
    fn create_alert(
        &self,
        symbol: &str,
        timeframe: &str,
        severity: AlertSeverity,
        message: String,
    ) -> IngestionAlert {
        let alert = IngestionAlert {
            id: uuid::Uuid::new_v4().to_string(),
            symbol: symbol.to_string(),
            timeframe: timeframe.to_string(),
            severity,
            message,
            created_at: Utc::now(),
            acknowledged: false,
        };

        let mut alerts = self.alerts.write().unwrap();
        alerts.push(alert.clone());

        // Keep only last 1000 alerts
        if alerts.len() > 1000 {
            alerts.drain(0..100);
        }

        alert
    }

    /// Get all active (unacknowledged) alerts
    pub fn get_active_alerts(&self) -> Vec<IngestionAlert> {
        let alerts = self.alerts.read().unwrap();
        alerts.iter().filter(|a| !a.acknowledged).cloned().collect()
    }

    /// Acknowledge an alert
    pub fn acknowledge_alert(&self, alert_id: &str) -> bool {
        let mut alerts = self.alerts.write().unwrap();
        if let Some(alert) = alerts.iter_mut().find(|a| a.id == alert_id) {
            alert.acknowledged = true;
            true
        } else {
            false
        }
    }

    /// Get status for a specific symbol/timeframe
    pub fn get_status(&self, symbol: &str, timeframe: &str) -> Option<IngestionStatus> {
        let statuses = self.statuses.read().unwrap();
        statuses.get(&Self::key(symbol, timeframe)).cloned()
    }

    /// Get all ingestion statuses
    pub fn get_all_statuses(&self) -> Vec<IngestionStatus> {
        let statuses = self.statuses.read().unwrap();
        statuses.values().cloned().collect()
    }

    /// Get summary statistics
    pub fn get_summary(&self) -> IngestionSummary {
        let statuses = self.statuses.read().unwrap();
        let alerts = self.alerts.read().unwrap();
        let now = Utc::now();

        let mut healthy = 0;
        let mut warning = 0;
        let mut critical = 0;

        for status in statuses.values() {
            if let Some(last_success) = status.last_success {
                let age = now - last_success;
                if age > self.config.stale_critical_threshold {
                    critical += 1;
                } else if age > self.config.stale_warning_threshold {
                    warning += 1;
                } else {
                    healthy += 1;
                }
            } else {
                critical += 1; // Never had successful ingestion
            }
        }

        IngestionSummary {
            total_symbols: statuses.len(),
            healthy_count: healthy,
            warning_count: warning,
            critical_count: critical,
            active_alerts: alerts.iter().filter(|a| !a.acknowledged).count(),
            total_alerts: alerts.len(),
        }
    }
}

impl Default for IngestionMonitor {
    fn default() -> Self {
        Self::new(IngestionMonitorConfig::default())
    }
}

/// Summary of ingestion health
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestionSummary {
    pub total_symbols: usize,
    pub healthy_count: usize,
    pub warning_count: usize,
    pub critical_count: usize,
    pub active_alerts: usize,
    pub total_alerts: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_success() {
        let monitor = IngestionMonitor::default();
        monitor.record_success("BTC", "1h", 100);

        let status = monitor.get_status("BTC", "1h").unwrap();
        assert_eq!(status.total_successes, 1);
        assert_eq!(status.consecutive_failures, 0);
    }

    #[test]
    fn test_record_failure_alerts() {
        let config = IngestionMonitorConfig {
            failure_alert_threshold: 2,
            ..Default::default()
        };
        let monitor = IngestionMonitor::new(config);

        monitor.record_failure("BTC", "1h", "API error");
        assert_eq!(monitor.get_active_alerts().len(), 0);

        monitor.record_failure("BTC", "1h", "API error");
        assert_eq!(monitor.get_active_alerts().len(), 1);
    }

    #[test]
    fn test_summary() {
        let monitor = IngestionMonitor::default();
        monitor.record_success("BTC", "1h", 100);
        monitor.record_success("ETH", "1h", 100);

        let summary = monitor.get_summary();
        assert_eq!(summary.total_symbols, 2);
        assert_eq!(summary.healthy_count, 2);
    }
}
