//! Test harness for strategy validation

use alphafield_core::{Bar, Signal, Strategy};

/// Test harness for validating strategy behavior
///
/// The harness provides utilities for testing signal generation
/// across different market conditions.
pub struct StrategyTestHarness;

impl StrategyTestHarness {
    /// Create a new test harness instance
    pub fn new() -> Self {
        Self
    }

    /// Test that a strategy generates expected signals
    ///
    /// # Arguments
    /// * `strategy` - The strategy to test
    /// * `bars` - Market data bars to feed to the strategy
    /// * `expectation` - Expected signal count constraint
    ///
    /// # Returns
    /// Ok(()) if expectations are met, Err(TestError) otherwise
    ///
    /// # Example
    /// ```
    /// let harness = StrategyTestHarness::new();
    /// let bars = generate_trending_market(100, 0.02);
    /// let mut strategy = GoldenCrossStrategy::default();
    ///
    /// let result = harness.test_signal_generation(
    ///     &mut strategy,
    ///     &bars,
    ///     SignalExpectation::AtLeast(1),
    /// );
    ///
    /// assert!(result.is_ok());
    /// ```
    pub fn test_signal_generation<S: Strategy>(
        &self,
        strategy: &mut S,
        bars: &[Bar],
        expectation: SignalExpectation,
    ) -> Result<(), TestError> {
        let signals = self.collect_signals(strategy, bars);
        expectation.verify(signals.len())
    }

    /// Collect all signals generated by a strategy over a series of bars
    ///
    /// # Arguments
    /// * `strategy` - The strategy to test
    /// * `bars` - Market data bars
    ///
    /// # Returns
    /// Vector of all signals generated
    pub fn collect_signals<S: Strategy>(&self, strategy: &mut S, bars: &[Bar]) -> Vec<Signal> {
        let mut signals = Vec::new();

        for bar in bars {
            if let Some(sigs) = strategy.on_bar(bar) {
                signals.extend(sigs);
            }
        }

        signals
    }

    /// Count signals of a specific type
    ///
    /// # Arguments
    /// * `signals` - Vector of signals to analyze
    /// * `signal_type` - Type of signal to count (Buy/Sell)
    ///
    /// # Returns
    /// Count of signals matching the type
    pub fn count_signals_by_type(
        &self,
        signals: &[Signal],
        signal_type: alphafield_core::SignalType,
    ) -> usize {
        signals
            .iter()
            .filter(|s| s.signal_type == signal_type)
            .count()
    }

    /// Verify signal quality metrics
    ///
    /// Checks that signals have proper metadata and timestamps
    ///
    /// # Arguments
    /// * `signals` - Vector of signals to validate
    ///
    /// # Returns
    /// Ok(()) if all signals are valid, Err(TestError) otherwise
    pub fn verify_signal_quality(&self, signals: &[Signal]) -> Result<(), TestError> {
        for signal in signals {
            // Verify signal strength is in valid range
            if signal.strength < 0.0 || signal.strength > 1.0 {
                return Err(TestError::InvalidSignalStrength(signal.strength));
            }

            // Verify signal has timestamp
            if signal.timestamp.timestamp() == 0 {
                return Err(TestError::InvalidSignalTimestamp);
            }
        }

        Ok(())
    }
}

impl Default for StrategyTestHarness {
    fn default() -> Self {
        Self::new()
    }
}

/// Expectations for signal generation tests
///
/// Used to specify constraints on the number of signals
/// a strategy should generate.
#[derive(Debug, Clone)]
pub enum SignalExpectation {
    /// Expect at least N signals
    AtLeast(usize),
    /// Expect at most N signals
    AtMost(usize),
    /// Expect exactly N signals
    Exactly(usize),
    /// Expect no signals
    None,
}

impl SignalExpectation {
    /// Verify that the actual signal count meets the expectation
    ///
    /// # Arguments
    /// * `count` - Actual number of signals generated
    ///
    /// # Returns
    /// Ok(()) if count meets expectation, Err(TestError) otherwise
    fn verify(&self, count: usize) -> Result<(), TestError> {
        match self {
            SignalExpectation::AtLeast(n) => {
                if count >= *n {
                    Ok(())
                } else {
                    Err(TestError::TooFewSignals {
                        expected: *n,
                        actual: count,
                    })
                }
            }
            SignalExpectation::AtMost(n) => {
                if count <= *n {
                    Ok(())
                } else {
                    Err(TestError::TooManySignals {
                        expected: *n,
                        actual: count,
                    })
                }
            }
            SignalExpectation::Exactly(n) => {
                if count == *n {
                    Ok(())
                } else {
                    Err(TestError::WrongSignalCount {
                        expected: *n,
                        actual: count,
                    })
                }
            }
            SignalExpectation::None => {
                if count == 0 {
                    Ok(())
                } else {
                    Err(TestError::UnexpectedSignals { count })
                }
            }
        }
    }
}

/// Errors that can occur during strategy testing
#[derive(Debug)]
pub enum TestError {
    /// Strategy generated fewer signals than expected
    TooFewSignals { expected: usize, actual: usize },
    /// Strategy generated more signals than expected
    TooManySignals { expected: usize, actual: usize },
    /// Strategy generated wrong number of signals
    WrongSignalCount { expected: usize, actual: usize },
    /// Strategy generated signals when none expected
    UnexpectedSignals { count: usize },
    /// Signal strength outside valid range [0, 1]
    InvalidSignalStrength(f64),
    /// Signal has invalid or missing timestamp
    InvalidSignalTimestamp,
    /// Strategy panicked during execution
    StrategyPanicked(String),
}

impl std::fmt::Display for TestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TestError::TooFewSignals { expected, actual } => {
                write!(f, "Expected at least {} signals, got {}", expected, actual)
            }
            TestError::TooManySignals { expected, actual } => {
                write!(f, "Expected at most {} signals, got {}", expected, actual)
            }
            TestError::WrongSignalCount { expected, actual } => {
                write!(f, "Expected exactly {} signals, got {}", expected, actual)
            }
            TestError::UnexpectedSignals { count } => {
                write!(f, "Expected no signals, got {}", count)
            }
            TestError::InvalidSignalStrength(strength) => {
                write!(f, "Signal strength {} outside valid range [0, 1]", strength)
            }
            TestError::InvalidSignalTimestamp => {
                write!(f, "Signal has invalid or missing timestamp")
            }
            TestError::StrategyPanicked(msg) => {
                write!(f, "Strategy panicked: {}", msg)
            }
        }
    }
}

impl std::error::Error for TestError {}

#[cfg(test)]
mod tests {
    use super::*;
    use alphafield_core::{Signal, SignalType};
    use chrono::Utc;

    #[test]
    fn test_harness_creation() {
        let harness = StrategyTestHarness::new();
        // Just verify it creates without panic
        let _ = harness;
    }

    #[test]
    fn test_signal_expectation_at_least() {
        let expectation = SignalExpectation::AtLeast(5);
        assert!(expectation.verify(5).is_ok());
        assert!(expectation.verify(10).is_ok());
        assert!(expectation.verify(4).is_err());
    }

    #[test]
    fn test_signal_expectation_at_most() {
        let expectation = SignalExpectation::AtMost(5);
        assert!(expectation.verify(5).is_ok());
        assert!(expectation.verify(3).is_ok());
        assert!(expectation.verify(6).is_err());
    }

    #[test]
    fn test_signal_expectation_exactly() {
        let expectation = SignalExpectation::Exactly(5);
        assert!(expectation.verify(5).is_ok());
        assert!(expectation.verify(4).is_err());
        assert!(expectation.verify(6).is_err());
    }

    #[test]
    fn test_signal_expectation_none() {
        let expectation = SignalExpectation::None;
        assert!(expectation.verify(0).is_ok());
        assert!(expectation.verify(1).is_err());
    }

    #[test]
    fn test_error_messages() {
        let err = TestError::TooFewSignals {
            expected: 5,
            actual: 3,
        };
        assert!(err.to_string().contains("at least 5 signals"));
        assert!(err.to_string().contains("got 3"));
    }
}
